### PR TITLE
Add azp yml

### PR DESCRIPTION
**Pull request by rmatsum836**
In reference to #1 having AZP with nightly builds.

### CODE REVIEW

**Comment by rmatsum836** [comment]
AZP builds are simple but passing.  Nightly builds are scheduled.

**Comment by mattwthompson** [comment]
It looks like it's working (there are green check marks on AZP) but this webpage hangs for me https://dev.azure.com/mosdef/mosdef/_build?definitionId=5&_a=summary&view=runs

**Comment by rmatsum836** [comment]
Hm not sure why that is, I'm able to access the page just fine.  Maybe it's because you're not added to AZP for this repo yet?

**Comment by mattwthompson** [comment]
Not sure, but if it looks fine for you we can merge this

**Pull request merged**
